# Use root/example as user/password credentials
version: '3.1'

services:
  # Web server
  
  web:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./src:/var/www/html/:ro
    - ./node_modules:/var/www/assets/node_modules/:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
    - php

  php:
    build: .
    volumes:
    - ./src:/var/www/html/:ro
    - ./vendor:/var/www/vendor/:ro
    environment:
      DEBUG_MODE: 'true'
      SQL_HOST: db
      SQL_USER: root
      SQL_PASSWORD: example

  # Database services

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
    - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:12344:8080

  # phpmyadmin:
  #     image: phpmyadmin/phpmyadmin
  #     environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_USER=root
  #     - PMA_PASSWORD=example
  #     restart: always
  #     ports:
  #     - 127.0.0.1:12345:80
  #     external_links:
  #       - db:db